name = "DockerPy"
uuid = "7b2ae67c-a082-49fb-8801-fe9170dc9342"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
VersionParsing = "81def892-9a0e-5fdd-b105-ffc91e053289"

[compat]
PyCall = "1.18.5"
VersionParsing = "1.1.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
